name: "cut-release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: false



jobs:
  update_sem_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          set -x
          sudo apt-get install -y node-semver
          if [ -z "$NEW_VERSION" ]; then
             echo "Current Version: $(cat VERSION)"
             semver -i patch $(cat VERSION) > VERSION
          else
             echo $NEW_VERSION > VERSION
          fi
          
          cat VERSION
          
        env:
          NEW_VERSION: ${{ inputs.version }}
