name: "cut-release"

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (leave blank for auto-increment)'
        required: false
jobs:
  cut_release:
    runs-on: ubuntu-22.04
    steps:
      - name: Install deps
        run: |
          sudo apt-get install build-essential python3-semver fakeroot -y
      - name: Checkout code 
        uses: actions/checkout@v3
      - name: Update VERSION file on checkout 
        run: |
          set -xeu -o pipefail
          CURRENT_VERSION=$(cat VERSION)
          echo "Current Version: $CURRENT_VERSION"
          if [ -z "$NEW_VERSION" ]; then
             NEW_VERSION=$(pysemver bump patch "$CURRENT_VERSION")
          fi
          echo $NEW_VERSION > VERSION
          echo "::set-output name=NEW_VERSION::$NEW_VERSION" 
        id: bump-version-file  
        env:
          NEW_VERSION: ${{ inputs.version }}
      - name: "Build & test"
        run: |
          ./autogen.sh
          ./configure
          fakeroot make distcheck
      - name: Commit VERSION file 
        uses: EndBug/add-and-commit@v9
        with:
          add: 'VERSION'
          message: "Release numactl ${{ steps.bump-version-file.outputs.NEW_VERSION }}"
          committer_name: GitHub Actions
          committer_email: actions@github.com
      - name: Create Tag
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ steps.bump-version-file.outputs.NEW_VERSION }}"
          message: "Release numactl ${{ steps.bump-version-file.outputs.NEW_VERSION }}"
      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: v${{ steps.bump-version-file.outputs.NEW_VERSION }}
          release_name: "Release ${{ steps.bump-version-file.outputs.NEW_VERSION }}"
          draft: true
          prerelease: false
          files: |
            numactl-*.tar.gz
